apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.default.svc.cluster.local:8200" ##DNS do serviço dentro do kubernetes. 
      path: "devops"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-policy-token"
          key: "token"
